apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: pet-clinic
  labels:
    deploy: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: pet-clinic-config-service-account
      containers:
      - image: "$CONTAINER_IMAGE"
        imagePullPolicy: Always
        name: config-server
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.3"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-server
              key: CONFIG_SERVER_URL
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: kv-secrets-pet-clinic-config-svc
              key: APP-INSIGHTS-CONNECTION-STRING
        - name: APPLICATIONINSIGHTS_CONFIGURATION_CONTENT
          value: >-
            {
                "role": {
                    "name": "config-server"
                  }
            }
        - name: GIT_CONFIG_REPO_URI
          valueFrom:
            secretKeyRef:
              name: kv-secrets-pet-clinic-config-svc
              key: GIT-REPO-URI
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: kv-secrets-pet-clinic-config-svc
              key: GIT-REPO-USERNAME
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kv-secrets-pet-clinic-config-svc
              key: GIT-REPO-PASSWORD
        - name: ENVIRONMENT
          value: AKS
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi: 
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-secrets-pet-clinic-config-svc

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: pet-clinic
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
  - protocol: TCP
    name: http
    port: 8888
    targetPort: 8888
