apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: pet-clinic
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
      - image: "$CONTAINER_IMAGE"
        imagePullPolicy: Always
        name: prometheus-server
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9091
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9091
            scheme: HTTP
          initialDelaySeconds: 30
          successThreshold: 1
        ports:
        - containerPort: 9091
          name: http
          protocol: TCP
        securityContext:
          privileged: false
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-server
              key: CONFIG_SERVER_URL
        - name: ENVIRONMENT
          value: AKS
        volumeMounts:
          - name: secrets-store01-inline
            mountPath: /mnt/secrets-store
            readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi: 
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-secrets-pet-clinic-app

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-server
  name: prometheus-server
  namespace: pet-clinic
spec:
  type: ClusterIP
  selector:
    app: prometheus-server
  ports:
  - protocol: TCP
    name: http
    port: 9091
    targetPort: 9091
