apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-server
  namespace: pet-clinic
  labels:
    app: grafana-server
spec:
  selector:
    matchLabels:
      app: grafana-server
  template:
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
        - image: "$CONTAINER_IMAGE"
          imagePullPolicy: Always
          name: grafana-server
          namespace: pet-clinic
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-server
  name: grafana-server
  namespace: pet-clinic
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana-server
  type: LoadBalancer
