apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tracing-server
  name: tracing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
      - image: "$CONTAINER_IMAGE"
        name: tracing-server
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9411
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9411
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        ports:
        - containerPort: 9411
          name: http
          protocol: TCP
        securityContext:
          privileged: false
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-server
              key: CONFIG_SERVER_URL
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: kv-secrets-pet-clinic-app
              key: PET-CLINIC-APP-INSIGHTS-CONNECTION-STRING
              optional: false
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: kv-secrets-pet-clinic-app
              key: PET-CLINIC-INSIGHTS-INSTRUMENTATION-KEY
              optional: false
        - name: APPLICATIONINSIGHTS_CONFIGURATION_CONTENT
          value: >-
            {
                "role": {   
                    "name": "tracing-server"
                  }
            }
        - name: ENVIRONMENT
          value: AKS
        volumeMounts:
          - name: secrets-store01-inline
            mountPath: /mnt/secrets-store
            readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi: 
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-secrets-pet-clinic-app
   
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tracing-server
  name: tracing-server
spec:
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: tracing-server
  type: ClusterIP