spring:
  application:
    name: admin-server
  config:
    import: configserver:${CONFIG_SERVER_URL}

# ---
# spring:
#   config:
#     activate:
#       on-profile: docker
#     import: configserver:http://config-server:8888


# ---
# spring:
#   config:
#     activate:
#       on-profile: azure-aks
#     import: configserver:http://config-server:8888
