spring:
  application:
    name: admin-server
  config:
    import: configserver:http://config-server:8888
# ---
# spring:
#   application:
#     name: admin-server
#   config:
#     activate:
#       on-profile: local
#     import: http://localhost:8888/
