spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
---
spring:
  application:
    name: admin-server
  config:
    activate:
      on-profile: local
    import: http://localhost:8888/
