apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets-pet-clinic-vet-svc
  namespace: pet-clinic
spec:
  provider: azure
  secretObjects:
    - secretName:  kv-secrets-pet-clinic-vet-svc
      type: Opaque
      data:
        - key: SPRING-DATASOURCE-URL
          objectName: PET-CLINIC-VET-SVC-SPRING-DATASOURCE-URL
        - key: SPRING-DS-USER
          objectName: PET-CLINIC-VET-SVC-SPRING-DS-USER
        - key: APP-INSIGHTS-CONNECTION-STRING
          objectName: PET-CLINIC-APP-INSIGHTS-CONNECTION-STRING
        - key: APP-INSIGHTS-INSTRUMENTATION-KEY
          objectName: PET-CLINIC-APP-INSIGHTS-INSTRUMENTATION-KEY 
  parameters:
    keyvaultName: "$KEYVAULT_NAME"
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "$VET_SVC_CLIENT_ID"
    objects:  |
      array:
        - |
          objectName: PET-CLINIC-VET-SVC-SPRING-DATASOURCE-URL
          objectAlias: PET-CLINIC-VET-SVC-SPRING-DATASOURCE-URL
          objectType: secret
        - |
          objectName: PET-CLINIC-VET-SVC-SPRING-DS-USER
          objectAlias: PET-CLINIC-VET-SVC-SPRING-DS-USER
          objectType: secret
        - |
          objectName: PET-CLINIC-APP-INSIGHTS-CONNECTION-STRING
          objectAlias: PET-CLINIC-APP-INSIGHTS-CONNECTION-STRING
          objectType: secret
        - |
          objectName: PET-CLINIC-APP-INSIGHTS-INSTRUMENTATION-KEY
          objectAlias: PET-CLINIC-APP-INSIGHTS-INSTRUMENTATION-KEY
          objectType: secret
    tenantId: "$TENANT_ID"