name: 98-Infra-test-aks

on:
  workflow_dispatch:

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure login in AKS Subscription # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure
        uses: azure/login@v1
        with:
          client-id: "${{secrets.AAD_CLIENT_ID}}"
          tenant-id: "${{secrets.AAD_TENANT_ID}}"
          subscription-id: "${{secrets.AKS_SUBSCRIPTION_ID}}"

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        
      - name: Setup kubelogin
        uses: azure/use-kubelogin@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          kubelogin-version: 'latest'
          
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{secrets.AKS_RESOURCE_GROUP}}'
          cluster-name: '${{secrets.AKS_NAME}}'
      
      - name: Test AKS connection
        run: |
          kubectl get nodes
          kubectl get pods --all-namespaces
      