name: 99-Continuous-Delivery

on:
  workflow_call:
    inputs:
      app_name:
        description: 'Application to deploy (todo-app, spring-petclinic-admin-server, ...)'
        required: true
        type: string
      version:
        description: 'App Version to deploy (i.e. 1.5.3)'
        type: string
        required: true
      deployment_suffix:
        description: 'K8S Deployment Suffix'
        type: string
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Application to deploy'
        required: true
        type: choice
        options:
          - 'todo-app'
          - 'spring-petclinic-admin-server'
          - 'spring-petclinic-api-gateway'
          - 'spring-petclinic-config-server'
          - 'spring-petclinic-customers-service'
          - 'spring-petclinic-discovery-server'
          - 'spring-petclinic-vets-service'
          - 'spring-petclinic-visits-service'
        default: 'todo-app'
      version:
        description: 'App Version to deploy (i.e. 1.5.3)'
        required: true
      deployment_suffix:
        description: 'K8S Deployment Suffix'

jobs:
  # for debugging purposes only
  preinit:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub Event context
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Event name
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: echo "$EVENT_NAME"
      # - name: Dump strategy context
      #   env:
      #     STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      #   run: echo "$STRATEGY_CONTEXT"
      # - name: Dump matrix context
      #   env:
      #     MATRIX_CONTEXT: ${{ toJson(matrix) }}
      #   run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
  deploy:
    needs: preinit
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Init
        id: init
        run: |
          releaseVersion=""
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
            releaseVersion="${{inputs.version}}"
            deploymentSuffix="${{inputs.deployment_suffix}}"
            appName="${{inputs.app_name}}"
          elif [[ "${{github.event_name}}" == "workflow_call" ]]; then
            releaseVersion="${{inputs.version}}"
            deploymentSuffix="${{inputs.deployment_suffix}}"
            appName="${{inputs.app_name}}"
          elif [[ "${{github.event_name}}" == "push" ]]; then
            releaseVersion="${{inputs.version}}"
            deploymentSuffix="${{inputs.deployment_suffix}}"
            appName="${{inputs.app_name}}"
          else
            echo "Unsupported event '${{github.event_name}}'. Exiting..."
            exit 1
          fi
          if [[ -z "$releaseVersion" ]]; then
            echo "RELEASE_VERSION is not set. Exiting..."
            exit 1
          fi
          dbName=""
          if [[ "${appName}" == "todo-app" ]]; then
            dbName="tododb"
          elif [[ "${appName}" == "spring-petclinic-customers-service" ]]; then
            dbName="petcliniccustomersdb"
          elif [[ "${appName}" == "spring-petclinic-vets-service" ]]; then
            dbName="petclinicvetssdb"
          elif [[ "${appName}" == "spring-petclinic-visits-service" ]]; then
            dbName="petclinicvisitsdb"
          fi
          echo "APP_NAME=${appName}" >> $GITHUB_OUTPUT
          echo "RELEASE_VERSION=${releaseVersion}" >> $GITHUB_OUTPUT
          echo "RELEASE_DIR_NAME=${appName}-${releaseVersion}" >> $GITHUB_OUTPUT
          echo "RELEASE_ARCHIVE_NAME=${appName}-${releaseVersion}.zip" >> $GITHUB_OUTPUT
          echo "RELEASE_FILE_NAME=${appName}-${releaseVersion}.jar" >> $GITHUB_OUTPUT
          echo "DEPLOYMENT_SUFFIX=$deploymentSuffix" >> $GITHUB_OUTPUT
          echo "DB_NAME=$dbName" >> $GITHUB_OUTPUT
      
      - uses: robinraju/release-downloader@v1.7
        with:
          tag: 'v${{steps.init.outputs.RELEASE_VERSION}}-${{steps.init.outputs.APP_NAME}}'
          fileName: "${{steps.init.outputs.RELEASE_ARCHIVE_NAME}}"

      - name: Check downloaded files
        run: |
          pwd
          ls -la
          if [[ ! -f "${{steps.init.outputs.RELEASE_ARCHIVE_NAME}}" ]]; then
            echo "'${{steps.init.outputs.RELEASE_ARCHIVE_NAME}}' does not exist."
            exit 1
          fi
      
      - name: Unzip archive
        run: |
          echo "Unzipping the release archive file: ${{steps.init.outputs.RELEASE_ARCHIVE_NAME}}"
          unzip ${{steps.init.outputs.RELEASE_ARCHIVE_NAME}}
          if [[ ! -f "${{steps.init.outputs.RELEASE_DIR_NAME}}/${{steps.init.outputs.RELEASE_FILE_NAME}}" ]]; then
            echo "'${{steps.init.outputs.RELEASE_DIR_NAME}}/${{steps.init.outputs.RELEASE_FILE_NAME}}' does not exist."
            exit 1
          fi

      - name: Azure login in AKS Subscription # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure
        uses: azure/login@v1
        with:
          client-id: "${{secrets.AAD_CLIENT_ID}}"
          tenant-id: "${{secrets.AAD_TENANT_ID}}"
          subscription-id: "${{secrets.PGSQL_SUBSCRIPTION_ID}}"

      - name: Add DB Firewall exception used for Schema sync
        if: ${{ steps.init.outputs.DB_NAME != '' }}
        run: |
          deploymentClientIP=`dig +short myip.opendns.com @resolver1.opendns.com.`
          az postgres flexible-server firewall-rule create --rule-name "AllowDeploymentClientIP" --resource-group ${{secrets.PGSQL_RESOURCE_GROUP}} --name ${{secrets.PGSQL_NAME}} --start-ip-address ${deploymentClientIP} --subscription "${{secrets.PGSQL_SUBSCRIPTION_ID}}"
      
      - name: Synchronize DB Schema
        if: ${{ steps.init.outputs.DB_NAME != '' }}
        env:
          RELEASE_DIR_NAME: ${{steps.init.outputs.RELEASE_DIR_NAME}}
          PGSQL_SERVER_NAME: '${{secrets.PGSQL_NAME}}.postgres.database.azure.com'
          DB_NAME: ${{steps.init.outputs.DB_NAME}}
        run: |
          export PGPASSWORD=`az account get-access-token --resource-type oss-rdbms --query "[accessToken]" --output tsv`
          psql --set=sslmode=require -h "${{env.PGSQL_SERVER_NAME}}" -p 5432 -d "${{env.DB_NAME}}" -U "${{secrets.DBA_GROUP_NAME}}" --file=./${{env.RELEASE_DIR_NAME}}/db/pgsql/schema.sql -v ON_ERROR_STOP=1
          psql --set=sslmode=require -h "${{env.PGSQL_SERVER_NAME}}" -p 5432 -d "${{env.DB_NAME}}" -U "${{secrets.DBA_GROUP_NAME}}" --file=./${{env.RELEASE_DIR_NAME}}/db/pgsql/data.sql -v ON_ERROR_STOP=1
      
      - name: Azure login in AKS Subscription # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure
        uses: azure/login@v1
        with:
          client-id: "${{secrets.AAD_CLIENT_ID}}"
          tenant-id: "${{secrets.AAD_TENANT_ID}}"
          subscription-id: "${{secrets.AKS_SUBSCRIPTION_ID}}"

      - name: Re-generate container image if needed
        env:
          APP_NAME: ${{steps.init.outputs.APP_NAME}}
          IMAGE_NAME: '${{steps.init.outputs.APP_NAME}}:${{steps.init.outputs.RELEASE_VERSION}}'
          CONTAINER_REGISTRY_NAME: ${{secrets.CONTAINER_REGISTRY_NAME}}
          RELEASE_VERSION: ${{steps.init.outputs.RELEASE_VERSION}}
          RELEASE_DIR_NAME: ${{steps.init.outputs.RELEASE_DIR_NAME}}
          VERSION: ${{steps.init.outputs.RELEASE_VERSION}}
        run: |
          imageExists=true
          repoName=`az acr repository list -n martinabrle --query "[?contains(@, '${{env.APP_NAME}}')]" -o tsv`
          echo "Repo name: $repoName"
          if [[ -z "${repoName}" ]]; then
            echo "Repo '${{env.APP_NAME}}' does not exist."
            imageExists=false
          else
            echo "Repo '${{env.APP_NAME}}' already exist."
            tagName=`az acr repository show-tags -n ${{env.CONTAINER_REGISTRY_NAME}} --repository ${{env.APP_NAME}} --query "[?contains(@, '${{env.RELEASE_VERSION}}')]" -o tsv`
            if [[ -z "${tagName}" ]]; then
              echo "Tag '${{env.RELEASE_VERSION}}' does not exist."
              imageExists=false
            else
              echo "Tag '${{env.RELEASE_VERSION}}' already exist."
            fi
          fi
          if [[ "${imageExists}" == "false" ]]; then
            cd ./${{env.RELEASE_DIR_NAME}}
            mv ./Dockerfile ./Dockerfile.tmp
            # Dockerfile syntax is driving me bonkers. This should work...
            cat ./Dockerfile.tmp | ARTIFACT_NAME_ARG=${{env.APP_NAME}} VERSION_ARG=${{env.VERSION}} envsubst > ./Dockerfile
            cat ./Dockerfile
            az acr build ./ -r ${{secrets.CONTAINER_REGISTRY_NAME}} -t "${{env.IMAGE_NAME}}" --file ./Dockerfile --subscription "${{secrets.CONTAINER_REGISTRY_SUBSCRIPTION_ID}}"
            cd ..
          fi
 
      - name: Test connection to AKS
        run: |
          az aks command invoke \
           --resource-group ${{secrets.AKS_RESOURCE_GROUP}} \
           --name ${{secrets.AKS_NAME}} \
           --command "kubectl get ns"

      - name: Deploy app into AKS
        env:
          DEPLOYMENT_SUFFIX: ${{steps.init.outputs.DEPLOYMENT_SUFFIX}}
          RELEASE_DIR_NAME: ${{steps.init.outputs.RELEASE_DIR_NAME}}
          CONTAINER_IMAGE: ${{secrets.CONTAINER_REGISTRY_NAME}}.azurecr.io/${{steps.init.outputs.APP_NAME}}:${{steps.init.outputs.RELEASE_VERSION}}
        run: |
          cat ./${{env.RELEASE_DIR_NAME}}/k8s/deployment.yml | CONTAINER_IMAGE=${{env.CONTAINER_IMAGE}} DEPLOYMENT_SUFFIX=${{env.DEPLOYMENT_SUFFIX}} envsubst > ./deployment.yml.tmp
          cat ./deployment.yml.tmp
          az aks command invoke \
           --resource-group ${{secrets.AKS_RESOURCE_GROUP}} \
           --name ${{secrets.AKS_NAME}} \
           --command "kubectl apply -f deployment.yml.tmp" \
           --file deployment.yml.tmp
      
      - name: Remove DB Firewall exception used for Schema sync
        if: ${{ steps.init.outputs.DB_NAME != '' }}
        run: |
          az postgres flexible-server firewall-rule delete --rule-name "AllowDeploymentClientIP" -g ${{secrets.PGSQL_RESOURCE_GROUP}} --name ${{secrets.PGSQL_NAME}} --subscription "${{secrets.PGSQL_SUBSCRIPTION_ID}}" --yes
      